= Quarkus Minecraft

Great inspiration taken from https://github.com/holly-cummins/quarkus-minecraft-observability-extension

== quarkus-minecraft-extension

The extension `quarkus-minecraft-extension` will add more loggers to our app and hook into places where the annotaion `javax.ws.rs.GET` is used.



.Create the Quarkus extension from scratch

[source,bash]
----
mvn io.quarkus.platform:quarkus-maven-plugin:create-extension -N
----

.Install the Quarkus extension locally

[source,bash]
----
cd quarkus-minecraft-extension
mvn install
----

.Structure in the extension
----
└─── quarkus-minecraft-extension
    ├── deployment
    ├── runtime
    ├── integration-tests
    └── pom.xml
----

=== Link

https://quarkus.io/guides/extension-codestart[Extension codestart - Quarkus]

== quarkus-minecraft-app

.Create the Quarkus app from scratch

[source,bash]
----
mvn io.quarkus:quarkus-maven-plugin:2.11.3.Final:create \
    -DprojectGroupId=dk.jarry \
    -DprojectArtifactId=quarkus-minecraft-app \
    -DclassName="dk.jarry.minecraft.todo.boundary.ToDoResource" \
    -Dpath="/todos"
----

.Add the extension quarkus-minecraft-extension to our Quarkus app (quarkus-minecraft-app)

Add this dependency to `quarkus-minecraft-app/pom.xml`
[source,xml]
----
<dependency>
  <groupId>dk.jarry</groupId>
  <artifactId>quarkus-minecraft-extension</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
----

.Start Quarkus in dev mode

[source,bash]
----
cd quarkus-minecraft-app
mvn compile quarkus:dev
----

.Have a look into the bytecode

[source,bash]
----
bytecode-viewer
----

Look in

- quarkus-minecraft-app/target/quarkus-app/app/quarkus-minecraft-app-1.0.0-SNAPSHOT.jar
- quarkus-minecraft-app/target/quarkus-app/quarkus/generated-bytecode.jar


== quarkus-mod

The `quarkusmod` will add an `UndertowJaxrsServer` to the Minecraft server and listen to port 8081.

We will use port 8081 to sendt reqest from our Quarkus app to MineCraft.

=== Start the Minecraft server

[source,bash]
----
cd quarkus-mod
./gradlew runServer
----

[TIP]
First time you start the Mincraft server you will have to accept the eula by changing eula=false to eula=true in the file `modded-minecraft/run/eula.txt`

== Minecraft client

You will need the Java edition of Minecraft. Start a multiplayer game, and connect to `http://localhost:25565`.

You will need to configure the client to allow you to `alt-tab` away from the client without it pausing and bringing up
a menu. Edit `options.txt` in
your [minecraft folder](https://gaming.stackexchange.com/questions/15664/can-i-alt-tab-out-of-minecraft-without-the-game-auto-pausing)
, and change `pauseOnLostFocus` to `false`.

----
pauseOnLostFocus:false
----


== Util

.Who is blocking port 8080

[source,bash]
----
lsof -i:8080 | grep LISTEN | awk '{print $2}'
----